name: Generate Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
    id-token: write
    pages: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload all to Google Drive (optional)
        uses: izzalDev/gdrive-upload-action@main
        with:
          filename: README.md